
POST http://localhost:5000/auth/register
Content-Type: application/json


{
  "username": "vuongthaonguy1en111",
  "password": "vuongthaonguyen111"
}

###


# POST http://localhost:5000/auth/login
# Content-Type: application/json

# {
#   "username": "vuongthaonguyen111",
#   "password": "vuongthaonguyen111"
# }


# ###

# GET http://localhost:5000/home
